import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';

import { AbstractEntity } from '../../common/database/abstract.entity';

@Schema({ timestamps: true })
export class ChatDocument extends AbstractEntity {
  @Prop()
  userId: string;

  @Prop()
  name: string;

  @Prop({ default: false })
  isPrivate: boolean;

  @Prop({ type: [String], default: [] })
  userIds: string[];

  // Auto-generated by Mongoose via @Schema({ timestamps: true })
  // Optional in TypeScript because they don't exist at creation time - Mongoose adds them on save
  // No @Prop() needed - timestamps: true handles schema definition automatically
  createdAt?: Date;
  updatedAt?: Date;
}

export const ChatSchema = SchemaFactory.createForClass(ChatDocument);

// Index for cursor-based pagination (sorted by latest message, then chat creation)
ChatSchema.index({ createdAt: -1, _id: -1 });
// The `userIds` multikey index enables efficient lookups for "find all chats where user X is a member".
ChatSchema.index({ userIds: 1 });
