import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';

import { AbstractEntity } from '../../common/database/abstract.entity';
import { MessageDocument } from '../messages/entities/message.document';

@Schema({ timestamps: true })
export class ChatDocument extends AbstractEntity {
  @Prop()
  userId: string;

  @Prop()
  name: string;

  @Prop([MessageDocument])
  messages: MessageDocument[];

  // Auto-generated by Mongoose via @Schema({ timestamps: true })
  // Optional in TypeScript because they don't exist at creation time - Mongoose adds them on save
  // No @Prop() needed - timestamps: true handles schema definition automatically
  createdAt?: Date;
  updatedAt?: Date;
}

export const ChatSchema = SchemaFactory.createForClass(ChatDocument);

// Indexes for cursor-based pagination (sorted by latest message, then chat creation)
// Supports the aggregation's $sort: { sortDate: -1, _id: -1 }
ChatSchema.index({ createdAt: -1, _id: -1 });
